language: python

jobs:
  include:
    - language: python
      dist: xenial
      python: "3.8"
      sudo: required

    - language: python
      dist: xenial
      python: "3.7"
      sudo: required

    - language: python
      dist: xenial
      python: "3.6"
      sudo: required
      
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  username: __token__
  password:
    secure: ZwjUKpUNV/ON41uRlqvK1vkFOGJhG6Wl27/gBhhwdvh4+n0QR8oRfY7618OeI6Jy7GTukm1/rCIRpE6h/HwVOChI4HYeKcBpq+276tKks3gjrOgs7kXvmULNjrJiUcdIDQv9P7g1M5SkU2mJPkUQgENwuo8fc9QPdyhBAtCvTvMcyLmHyBjjKpv3eyqfkOMwkLaKhCXsMD98VqD151Q4g34JOnX3/zTwVYcpk8ofufQOkCldrCJgCmGzjNIyq0bnAMdahkSXScyxR5tuMM/4F+qAmsT5HCUl9CXdESclcJ4YvhUvS/QRx9NjjAhRRQvIT8YflX6s3OlBb55VtlxSoIjjvGKiw8QxsYdWbP10c1miBbTSWrGGqVAURufCnK/ioRS2v60SUCiGMCknhtYfK6Fqy6kjorkAw0QuCqMUPpgPXve2Ip86oX2VZGIZXT+S0UsHezLjN+J6wT7/Lla0aY52rZLS32acf9JhyjGekbJTjcaXoJgA3ylKw4mXIZ+cV4++wqaVBNTUdpmTqBhdFHmOfzUQHgdyL/zqlGZyv/BTW5nStd2TvX6UsHayw/j5xJ0T86XC5WjwdcHJuPuh4gG1+ms7hPHYxj9HzMCfj5xiLnTKxt0iJCdiaffBmLlYDY6kl0vo7Tn3vS0wxoXV210A7AKtr6g1FfnXmYVLrrE=
  on:
    tags: true
    repo: msyriac/pyfisher
    python: 3.8

addons:
  apt_packages:
  - gfortran
    
